# locales/sport_tennis.py

TENNIS_MAIN_TEXTS = {
    "ru": "🎾 **Теннисный хаб и спортивная экосистема**\n\nБольшой теннис для меня — это игра высоких скоростей и стратегического мышления. Я активно играю любительские турниры в РФ, Франции и Израиле, посещаю мировые чемпионаты и развиваю собственные теннисные проекты. Выберите интересующее вас направление:",
    "en": "🎾 **Tennis Hub & Sports Ecosystem**\n\nFor me, tennis is a game of high speeds and strategic calculations. I actively compete in amateur tournaments across Russia, France, and Israel, attend global championships, and develop my own tennis ventures. Select an option below:",
    "fr": "🎾 **Hub de Tennis & Écosystème Sportif**\n\nLe tennis est un jeu de grande vitesse et de calculs stratégiques. Je participe activement à des tournois amateurs en Russie, en France et en Israël, j'assiste aux championnats mondiaux et je développe mes propres projets. Choisissez une option ci-dessous :",
    "he": "🎾 **מרכז הטניס ואקוסיסטם הספורט**\n\nטניס עבורי הוא משחק של מהירויות גבוהות וחישובים אסטרטגיים. אני משתתפת באופן פעיל בטורנירים לחובבים ברוסיה, צרפת וישראל, מבקרת באליפויות העולם ומפתחת מיזמי טניס משלי. בחר אפשרות למטה:"
}

TENNIS_GEO_TEXTS = {
    "ru": "🌍 **Международный корт: Мой опыт и база клубов**\n\n• 🇷🇺 **Россия:** Накоплена закрытая база лучших клубов и организаторов любительских турниров. Знаю, где идеальный грунт и хард, и как быстро войти в локальное теннисное комьюнити.\n• 🇫🇷 **Франция:** Могу детально проконсультировать, как иностранцу официально купить французскую теннисную лицензию (FFT), как устроена местная система рейтингов и внутренние клубные правила.\n• 🇮🇱 **Израиль:** Имею прямые контакты ведущих теннисных академий и клубов (Тель-Авив, Герцлия), которые регулярно проводят открытые соревнования.",
    "en": "🌍 **Global Court: Experience & Club Network**\n\n• 🇷🇺 **Russia:** A curated database of premium clubs and amateur tournament organizers. I know where to find the best clay or hard courts and how to access local tennis communities.\n• 🇫🇷 **France:** Comprehensive guidance on how to officially purchase a French tennis license (FFT) as a foreigner, alongside insights into the local rating matrix and club regulations.\n• 🇮🇱 **Israel:** Direct contacts with elite tennis academies (Tel Aviv, Herzliya) that actively manage open matches and competitive tournaments.",
    "fr": "🌍 **Court International : Expérience & Réseau**\n\n• 🇷🇺 **Russie :** Base de données des meilleurs clubs et organisateurs de tournois amateurs. Je sais où trouver les meilleurs courts en terre battue ou en dur.\n• 🇫🇷 **France :** Conseils complets sur la façon d'acheter officiellement une licence de tennis française (FFT) en tant qu'étranger, le système de classement et les règles des clubs.\n• 🇮🇱 **Israël :** Contacts directs avec les académies de tennis d'élite (Tel Aviv, Herzliya) qui organisent régulièrement des tournois ouverts.",
    "he": "🌍 **מגרש בינלאומי: ניסיון ומאגר מועדונים**\n\n• 🇷🇺 **רוסיה:** מאגר מובחר של המועדונים הטובים ביותר ומארגני טורנירים לחובבים. אני יודעת איפה למצוא את מגרשי החימר או המשטח הקשה הטובים ביותר ואיך להיכנס לקהילת הטניס המקומית.\n• 🇫🇷 **צרפת:** ייעוץ מפורט כיצד אזרח זר יכול לרכוש רשמית רישיון טניס צרפתי (FFT), כיצד בנויה מערכת הדירוג המקומית ותקנון המועדונים.\n• 🇮🇱 **ישראל:** קשרים ישירים עם אקדמיות הטניס המובילות (תל אביב, הרצליה) המארגנות באופן קבוע תחרויות פתוחות."
}

TENNIS_LIVE_TEXTS = {
    "ru": "🏆 **Турниры от первого лица & Трансляции**\n\nЯ регулярно посещаю крупные международные чемпионаты и делюсь инсайдами, атмосферой и аналитикой матчей прямо с трибун кортов.\n\nВ этом разделе вы можете найти сетки текущих любительских турниров с моим участием, а также проверенные ссылки на качественные трансляции матчей ATP/WTA.",
    "en": "🏆 **Live Tournaments & Broadcasts**\n\nI regularly attend major international championships, sharing firsthand insights, court atmosphere, and match analysis directly from the stands.\n\nHere you can find amateur tournament brackets featuring my matches, alongside verified streaming links for ATP/WTA tours.",
    "fr": "🏆 **Tournois en Direct & Diffusions**\n\nJe vis régulièrement les grands championnats internationaux depuis les tribunes, partageant mes analyses de match et l'ambiance du court.\n\nRetrouvez ici les tableaux des tournois amateurs auxquels je participe, ainsi que des liens vérifiés pour les diffusions ATP/WTA.",
    "he": "🏆 **טורנירים ממקור ראשון ושידורים**\n\nאני מבקרת באופן קבוע באליפויות בינלאומיות גדולות ומשתפת תובנות, אווירה וניתוח משחקים ישירות מיציעי המגרשים.\n\nבמדור это תוכלו למצוא לוחות משחקים של טורנירי חובבים בהשתתפותי, לצד קישורים מאומתים איכותיים לשידורי ATP/WTA."
}

TENNIS_SHOP_TEXTS = {
    "ru": "🛍 **Реферальный Pro-Shop: Теннисная мода & Экипировка**\n\nСтиль на корте важен так же, как и техника удара. В моём реферальном магазине собран проверенный Premium-ассортимент теннисной одежды, профессиональных ракеток и аксессуаров со скидками от моих партнеров.\n\nНажмите кнопку ниже, чтобы открыть каталог одежды и экипировки👇",
    "en": "🛍 **Referral Pro-Shop: Tennis Fashion & Gear**\n\nOn-court style is just as vital as swing technique. My referral shop features a curated premium selection of tennis apparel, professional rackets, and accessories with exclusive partner discounts.\n\nClick the button below to browse the fashion and gear catalog 👇",
    "fr": "🛍 **Pro-Shop de Parrainage : Mode Tennis & Équipement**\n\nLe style sur le court est tout aussi vital que la technique. Ma boutique propose une sélection premium de vêtements de tennis, de raquettes professionnelles et d'accessoires avec des remises exclusives.\n\nCliquez sur le bouton ci-dessous pour parcourir le catalogue 👇",
    "he": "🛍 **אופנת טניס וציוד (Shop-Pro חנות שותפים)**\n\nסגנון על המגרש חשוב לא פחות מטכניקת החבטה. בחנות השותפים שלי נאסף מגוון פרימיום מאומת של בגדי טניס, מחבטים מקצועיים ואביזרים עם הנחות בלעדיות מהשותפים שלי.\n\nלחץ על הכפתור למטה כדי לפתוח את קטלוג האופנה והציוד 👇"
}

TENNIS_THEORY_TEXTS = {
    "ru": "🔒 **Теннисная теория & Лайфхаки (Premium)**\n\nДобро пожаловать в закрытый клуб теннисной аналитики! Доступ к этому разделу открывается по платной подписке.\n\n**Что внутри:**\n• Эксклюзивные разборы тактических схем игры на грунте против харда.\n• Лайфхаки по ментальной устойчивости во время тай-брейков.\n• Видео-разборы техники ударов от ведущих тренеров академий.\n\nСтоимость доступа: **990 ₽ / месяц** (или эквивалент в валюте).",
    "en": "🔒 **Tennis Theory & Hacks (Premium)**\n\nWelcome to the private tennis analytics club! Access to this exclusive section requires an active subscription.\n\n**Inside the Club:**\n• Tactical breakdowns: playing on clay vs. hard courts.\n• Psychological lifehacks for maintaining focus during critical tie-breakers.\n• Video breakdowns of striking techniques from elite academy coaches.\n\nSubscription fee: **$12 / month**.",
    "fr": "🔒 **Théorie du Tennis & Astuces (Premium)**\n\nBienvenue dans le club privé d'analyse du tennis ! L'accès à cette section exclusive nécessite un abonnement actif.\n\n**Contenu du Club :**\n• Analyses tactiques : jouer sur terre battue vs. courts en dur.\n• Astuces psychologiques pour rester concentré pendant les tie-breaks.\n• Analyses vidéo des techniques de frappe par des entraîneurs d'élite.\n\nFrais d'abonnement : **12 € / mois**.",
    "he": "🔒 **תיאוריית טניס וטיפים (Premium)**\n\nברוכים הבאים למועדון הסגור של אנליטיקת טניס! הגישה למדור בלעדי זה נפתחת באמצעות מנוי בתשלום.\n\n**מה בפנים:**\n• ניתוחים טקטיים בלעדיים של תוכניות משחק על חימר מול משטח קשה •\n• טיפים לחוסן מנטלי במהלך נקודות שובר שוויון (Tie-breaks) •\n• ניתוחי וידאו של טכניקת חבטות ממאמנים מובילים באקדמיות •\n\nעלות הגישה: **12$ / חודש**"
}
