# locales/sport_travel.py

TRAVEL_MAIN_TEXTS = {
    "ru": "✈ **Дневник путешествий и геополитический кругозор**\n\nДля меня путешествия — это не просто отдых, а способ изучения международных рынков, культурных кодов и расширения ментальных границ. Здесь вы можете изучить географию моих визитов или открыть мой личный чек-лист для эффективных командировок.",
    "en": "✈ **Travel Diary & Global Horizon**\n\nFor me, traveling is more than leisure; it is a method for analyzing international markets, understanding cultural frameworks, and expanding horizons. Explore the geography of my visits or access my corporate travel checklist below.",
    "fr": "✈ **Carnet de Voyage & Horizon Global**\n\nPour moi, voyager est un moyen d'analyser les marchés internationaux, de comprendre les codes culturels et d'élargir mes horizons. Explorez la géographie de mes déplacements ou accédez à ma liste de contrôle.",
    "he": "✈ **יומן מסעות ואופק גלובלי**\n\nעבורי, נסיעות הן לא רק פנאי, אלא כלי לניתוח שווקים בינלאומיים, הבנת קודים תרבותיים והרחבת אופקים. חקרו את גיאוגרפיית הביקורים שלי או קבלו גישה לרשימת הציוד שלי למטה."
}

TRAVEL_GEOGRAPHY_TEXTS = {
    "ru": "🗺 **География визитов и executive-заметки:**\n\n• 🇮🇱 **Израиль (Тель-Авив):** Место моей академической магистратуры Sofaer Global MBA. Уникальная экосистема стартапов, высокоинтенсивный нетворкинг и синергия технологий.\n• 🇪🇺 **Европа (Франция, Италия, Германия):** Изучение классической архитектуры, операционных стандартов европейского ритейла и локального арт-рынка.\n• 🌍 **Ближний Восток & Азия:** Анализ масштабирования финтех-платформ и логистических цепочек в новых экономических хабах.",
    "en": "🗺 **Geography of Visits & Executive Insights:**\n\n• 🇮🇱 **Israel (Tel Aviv):** Home to my academic track at Sofaer Global MBA. A unique startup ecosystem, high-intensity networking, and tech synergy.\n• 🇪🇺 **Europe (France, Italy, Germany):** Exploring classical architecture, European retail operational excellence, and local art markets.\n• 🌍 **Middle East & Asia:** Analyzing fintech expansion frameworks and supply chain models across emerging global economic hubs.",
    "fr": "🗺 **Géographie des Déplacements & Perspectives :**\n\n• 🇮🇱 **Israël (Tel Aviv) :** Lieu de mon Master Sofaer Global MBA. Un écosystème unique de startups, un réseautage intense et une synergie technologique.\n• 🇪🇺 **Europe (France, Italie, Allemagne) :** Analyse de l'architecture classique, de l'excellence opérationnelle du retail européen et du marché de l'art.\n• 🌍 **Moyen-Orient & Asie :** Étude du développement des plateformes fintech et des chaînes logistiques.",
    "he": "🗺 **גיאוגרפיית ביקורים ותובנות ניהוליות:**\n\n• 🇮🇱 **ישראל (תל אביב):** הבית של התואר השני שלי ב-Sofaer Global MBA. אקוסისტם ייחודי של סטארטאפים, נטוורקינג בעצימות גבוהה וסינרגיה טכנולוגית.\n• 🇪🇺 **אירופה (צרפת, איטליה, גרמניה):** חקירת ארכיטקטורה קלאסית, מצוינות תפעולית בקמעונאות אירופית ושוקי אמנות מקומיים.\n• 🌍 **המזרח התיכון ואסיה:** ניתוח מסגרות להרחבת פינטק ומודלים של שרשרת אספקה במרכזים כלכליים מתמתחים."
}

TRAVEL_TOOLKIT_TEXTS = {
    "ru": "🧮 **Travel Toolkit: Эффективный тайм-менеджмент в дороге**\n\nМой личный чек-лист для оптимизации частых перемещений:\n\n1. 📱 **Цифровой суверенитет:** Клонирование доступов к критическим enterprise-системам, оффлайн-карты, eSIM под каждый регион.\n2. 💳 **Фин-комплаенс:** Распределение ликвидности между международными счетами, подготовка мультивалютных карт и крипто-кошельков.\n3. 🧳 **Оптимизация багажа:** Принцип капсульного гардероба (Smart Casual / Executive), позволяющий путешествовать строго с ручной кладью без потери статусности на деловых встречах.",
    "en": "🧮 **Travel Toolkit: Efficient Time-Management on the Road**\n\nMy corporate checklist for high-frequency travel optimization:\n\n1. 📱 **Digital Sovereignty:** Backup access to critical enterprise systems, offline vector maps, localized eSIM profiles.\n2. 💳 **Financial Compliance:** Capital allocation across international accounts, active multi-currency card setups, and secure wallets.\n3. 🧳 **Luggage Architecture:** Capsule wardrobe strategy (Smart Casual / Executive) for traveling strictly with carry-on luggage without compromising business presentation standards.",
    "fr": "🧮 **Travel Toolkit : Gestion du Temps en Déplacement**\n\nMa liste de contrôle personnelle pour optimiser les voyages fréquents :\n\n1. 📱 **Souveraineté Numérique :** Sauvegarde des accès aux systèmes d'entreprise, cartes hors ligne, profils eSIM locaux.\n2. 💳 **Conformité Financière :** Répartition des capitaux sur des comptes internationaux, cartes multidevises actives.\n3. 🧳 **Bagage Optimisé :** Stratégie de garde-robe capsule (Smart Casual / Executive) pour voyager uniquement avec un bagage à main.",
    "he": "🧮 **Travel Toolkit: ניהול זמן יעיל בדרכים**\n\nרשימת הבדיקה הניהולית שלי לאופטימיזציה של נסיעות בתדירות גבוהה:\n\n1. 📱 **ריבונות דיגיטלית:** גיבוי גישה למערכות ארגוניות קריטיות, מפות אופליין, פרופילי eSIM מקומיים.\n2. 💳 **תאימות פיננסית:** הקצאת הון בין חשבונות בינלאומיים, הגדרת כרטיסים רב-מטבעיים פעילים.\n3. 🧳 **ארכיטקטורת כבודה:** אסטרטגיית מלתחת קפסולה (Smart Casual / Executive) לנסיעה עם כבודת יד בלבד מבלי להתפשר על סטנדרט ההצגה העסקית."
}
