# locales/sport_horse.py

HORSE_MAIN_TEXTS = {
    "ru": "🏇 **Конный спорт: Грация, Выездка и Аналитика скачек**\n\nДля меня конный спорт делится на две важные составляющие: личная верховая езда (выезды и тренировки) и глубокая математическая аналитика мировых скачек. Выберите интересующее вас направление:",
    "en": "🏇 **Equestrian Sport: Grace, Dressage & Race Analytics**\n\nFor me, equestrian sport is divided into two vital components: personal horse riding (training & trails) and advanced mathematical analytics of global horse racing. Select a section below:",
    "fr": "🏇 **Sports Équestres : Grâce, Dressage & Analytique**\n\nPour moi, le sport équestre se divise en deux volets : l'équitation personnelle (entraînements, balades) et l'analyse mathématique des courses mondiales. Choisissez une section :",
    "he": "🏇 **ספורט רכיבה: גרציה, דרסאז' ואנליטיקת מרוצים**\n\nעבורי, ספורט הרכיבה מחולק לשני מרכיבים חיוניים: רכיבה אישית על סוסים (אימונים וטיולים) ואנליטיקה מתמטית מתקדמת של מרוצי סוסים עולמיים. בחר סעיף למטה:"
}

HORSE_RIDING_TEXTS = {
    "ru": "🌾 **Мой опыт верховой езды: Тренировки и прогулки**\n\nЛичная верховая езда для меня — это идеальный баланс контроля, физической выносливости и ментальной синхронизации с животным.\n\n• **Спортивные тренировки:** Развитие баланса, правильной посадки и управления на разных аллюрах (шаг, рысь, галоп).\n• **Конные прогулки:** Маршруты по пересеченной местности в живописных локациях РФ и за рубежом для перезагрузки и поиска вдохновения.",
    "en": "🌾 **My Horse Riding Experience: Training & Trail Rides**\n\nPersonal horse riding for me is a perfect equilibrium of absolute control, physical endurance, and deep mental alignment with the animal.\n\n• **Athletic Training:** Mastering posture, core balance, and precise command execution across basic gaits (walk, trot, canter).\n• **Trail Riding:** Cross-country routes in breathtaking locations within Russia and abroad, designed for strategic reflection and mental reboots.",
    "fr": "🌾 **Mon Expérience Équestre : Entraînements & Balades**\n\nL'équitation est pour moi un équilibre parfait entre contrôle absolu, endurance physique et harmonie mentale avec l'animal.\n\n• **Entraînement sportif :** Maîtrise de la posture, de l'équilibre et exécution des ordres aux différentes allures (pas, trot, galop).\n• **Randonnées équestres :** Itinéraires en pleine nature dans des endroits magnifiques pour se ressourcer.",
    "he": "🌾 **ניסיון הרכיבה שלי: אימונים וטיולי שטח**\n\nרכיבה אישית עבורי היא איזון מושלם של שליטה מוחלטת, סיבולת פיזית וסנכרון מנטלי עמוק עם בעל החיים.\n\n• אימונים ספורטיביים:** פיתוח שיווי משקל, יציבה נכונה ושליטה במקצבים השונים (הליכה, טרוט, קאנטר) •\n• טיולי רכיבה:** מסלולים בשטח פתוח בלוקיישנים מרהיבים בארץ ובחו''ל לטעינת אנרגיות והשראת מחשבה •"
}

HORSE_RACING_TEXTS = {
    "ru": "📊 **Аналитика скачек, Ипподромы и Стратегии ставок**\n\nМировые скачки — это индустрия больших данных, где правильный алгоритмический анализ превосходит случайность. Я глубоко разбираюсь в структуре этого рынка:\n\n• **География ипподромов:** Обзоры ключевых мировых площадок (Англия, Франция, ОАЭ) и правила проведения элитных кубков.\n• **Стратегии прогнозирования:** Как на основе формы лошади, покрытия трека, веса жокея и движения коэффициентов определять валуйные ставки.\n\nИспользуйте кнопки ниже, чтобы перейти на наш специализированный канал аналитики скачек 👇",
    "en": "📊 **Race Analytics, Racecourses & Betting Strategies**\n\nGlobal horse racing is a big-data industry where programmatic analysis systematically beats luck. I specialize in decoding this high-yield market:\n\n• **Racecourse Geography:** Overviews of premier global venues (UK, France, UAE) and elite cup operational guidelines.\n• **Predictive Frameworks:** How to identify high-value bets based on horse metrics, track conditions, jockey weight, and real-time odds movement.\n\nUse the buttons below to access our dedicated horse racing analytics channel 👇",
    "fr": "📊 **Analyse des Courses, Hippodromes & Paris**\n\nLes courses mondiales sont une industrie de Big Data. Je me spécialise dans le décryptage de ce marché à haut rendement :\n• **Géographie des hippodromes :** Présentation des sites mondiaux majeurs (Royaume-Uni, France, Émirats) et des règles des coupes d'élite.\n• **Stratégies prédictives :** Comment identifier les paris de valeur selon les métriques du cheval, l'état de la piste et l'évolution des cotes.",
    "he": "📊 **אנליטיקת מרוצים, היפודרומים ואסטרטגיות הימורים**\n\nמרוצי סוסים עולמיים הם תעשיית ביג-דאטה שבה ניתוח אלגוריתמי מנצח את המזל באופן שיטתי. אני מתמחה בפיענוח השוק הזה:\n• גיאוגרפיית היפודרומים:** סקירות של המסלולים המובילים בעולם (בריטניה, צרפת, איחוד האמירויות) ותקנוני גביעי העילית •\n• מסגרות חיזוי:** כיצד לזהות הימורים בעלי ערך גבוה על סמך מדדי הסוס, תנאי המסלול, משקל הג'וקי ותנועת היחסים •"
}

HORSE_ROBOT_TEXTS = {
    "ru": "🤖 **Платный AI-Робот Анализатор ставок**\n\nАвтоматизируйте свои прогнозы с помощью нашего Machine Learning алгоритма! Робот в реальном времени обрабатывает массивы исторических данных скачек, оценивает вероятности и выдает готовые сигналы с проходимостью более 78%.\n\n**Условия доступа:**\n• Подключение к сигналам робота в Telegram.\n• Прямые реферальные ссылки на проверенных букмекеров с бонусами на первый депозит.\n\nСтоимость подписки на робота: **1 490 ₽ / месяц**.",
    "en": "🤖 **Paid AI Bet Analyzer & Race Bot**\n\nAutomate your predictive models with our Machine Learning algorithm! The bot processes vast arrays of historical racing data in real-time, models probabilities, and delivers signals with a 78%+ win rate.\n\n**Access & Infrastructure:**\n• Direct integration with the Telegram automated signal bot.\n• Referral betting links to verified bookmakers with sign-up deposit bonuses.\n\nSubscription fee: **$19 / month**.",
    "fr": "🤖 **Robot Analyseur de Paris IA (Payant)**\n\nAutomatisez vos pronostics grâce à notre algorithme de Machine Learning ! Le robot traite d'immenses volumes de données en temps réel et livre des signaux avec un taux de réussite de 78%+.\n\nFrais d'abonnement : **19 € / mois**.",
    "he": "🤖 **רובוט אנליטי AI בתשלום לניתוח הימורים**\n\nהפוך את התחזיות שלך לאוטומטיות באמצעות אלגוריתם ה-Machine Learning שלנו! הרובוט מעבד מאגרי נתונים היסטוריים בזמן אמת ומספק אותות (Signals) עם אחוזי הצлחה של מעל 78%.\n\nעלות מנוי לרובוט: **19$ / חודש**"
}
